### PR TITLE
EXP: Replace Travis CI with GitHub Actions

### LINKED ISSUE #28: TST: Use GitHub Actions
Not sure if this repo is still active or not. If so, maybe can use https://github.com/peaceiris/actions-gh-pages

### PR DESCRIPTION
**Pull request by pllim**
Fix #28 .

Disclaimer: No idea if the pushing to GH pages actually works or not. This is a theoretical implementation. But we don't really need to make it work until we decide to revive this repo, so good enough for now?

p.s. @Cadair , ironically enough, I cannot find any official support from GitHub Actions to support publishing to GH Pages. I see third-party apps in the marketplace but nothing canon. If you find something, please let me know!

Also see https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables for supported env vars.

### CODE REVIEW

**Comment by pllim** [comment]
Hmm. Didn't kick off anything at https://github.com/pllim/astropy-dashboard/actions 🤷

**Comment by pllim** [comment]
Things don't quite work over at https://github.com/pllim/astropy-dashboard/actions . Should we spend more time on this, or simply archive this repo for now? We can always unarchive if we ever need it again.

**Comment by astrofrog** [comment]
I don't think we should archive this repo unless we actually decide to no longer maintain it. But I think this is a puppy worth keeping!

**Comment by pllim** [comment]
> puppy worth keeping

In that case:

* Simply remove `.travis.yml` for now and implement Actions when we actually need it? **OR**
* Try to fix it here?

**Pull request closed without merging**
